name: interview_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutter_form_builder: ^10.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.2
  go_router: ^14.8.1
  responsive_framework: ^1.5.1
  http: ^1.3.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  google_generative_ai: ^0.4.6
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  equatable: ^2.0.7
  stream_transform: ^2.1.1
  bloc_concurrency: ^0.3.0
  cloud_firestore: ^5.6.6
  uuid: ^4.5.1
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/message_fill.svg
    - assets/svgs/eye_stroke.svg
    - assets/svgs/eye-off_stroke.svg

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf

        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300

        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500

        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
