// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApajVqCR6GQG5x_x5-OfQIhbd1UaBFwrs',
    appId: '1:712323749777:web:012ba039bb24c33794ac30',
    messagingSenderId: '712323749777',
    projectId: 'interview-18f8f',
    authDomain: 'interview-18f8f.firebaseapp.com',
    storageBucket: 'interview-18f8f.firebasestorage.app',
    measurementId: 'G-ER2TY51R4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP460GT4gdtPTJjpnZ1uHPPaLvOs_eb_4',
    appId: '1:712323749777:android:ee25dda5f93d633894ac30',
    messagingSenderId: '712323749777',
    projectId: 'interview-18f8f',
    storageBucket: 'interview-18f8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm5gdfPHYFi3c07XkccCKWU45a9HtiRcc',
    appId: '1:712323749777:ios:a8c065c9ab7c684794ac30',
    messagingSenderId: '712323749777',
    projectId: 'interview-18f8f',
    storageBucket: 'interview-18f8f.firebasestorage.app',
    iosBundleId: 'com.example.interviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm5gdfPHYFi3c07XkccCKWU45a9HtiRcc',
    appId: '1:712323749777:ios:a8c065c9ab7c684794ac30',
    messagingSenderId: '712323749777',
    projectId: 'interview-18f8f',
    storageBucket: 'interview-18f8f.firebasestorage.app',
    iosBundleId: 'com.example.interviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApajVqCR6GQG5x_x5-OfQIhbd1UaBFwrs',
    appId: '1:712323749777:web:de199ea27ad3a53994ac30',
    messagingSenderId: '712323749777',
    projectId: 'interview-18f8f',
    authDomain: 'interview-18f8f.firebaseapp.com',
    storageBucket: 'interview-18f8f.firebasestorage.app',
    measurementId: 'G-YTVS9460N3',
  );
}
